name: huge_listview_example
description: Demonstrates how to use the huge_listview plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  huge_listview: ^2.0.10
  flutter_lints: ^2.0.2

dependency_overrides:
  huge_listview:
    path: ../

flutter:
  uses-material-design: true
