name: huge_listview
description: A performant list with any number of items.
version: 2.0.3
homepage: https://github.com/deakjahn/huge_listview

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  quiver: ^3.1.0
  scrollable_positioned_list: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
